services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    Vankosoft\AgentBundle\Controller\ActionsController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_application.repository.application'
