vs_agent_actions_index:
    path: /vs-agent/actions/list
    controller: Vankosoft\AgentBundle\Controller\ActionsController::index

vs_agent_actions_show_broken_virtual_host:
    path: /vs-agent/actions/broke-virtual-host
    controller: Vankosoft\AgentBundle\Controller\ActionsController::showBrokenVirtualHost

vs_agent_actions_broke_virtual_host:
    path: /vs-agent/actions/broke-virtual-host
    controller: Vankosoft\AgentBundle\Controller\ActionsController::brokeVirtualHost
